Repository Stremio/stremio-web, pull requests merged in 2024-11, with the labels that each got.

#727 fix: modal dialog styles issues
  src/common/ModalDialog/ModalDialog.js
  src/common/ModalDialog/styles.less
Labels: quick fix

#730 fix: bug when clicking on mark as watched button
  src/routes/MetaDetails/VideosList/Video/Video.js
Labels: quick fix

#645 feat(player): add seek action and handle seeking player state
  package-lock.json
  package.json
  src/routes/Player/Player.js
  src/routes/Player/usePlayer.d.ts
  src/routes/Player/usePlayer.js
Labels: core

#731 Fix: styles on metaDetails / Streams page
  src/common/Multiselect/styles.less
  src/routes/MetaDetails/StreamsList/Stream/styles.less
  src/routes/MetaDetails/StreamsList/styles.less
Labels: quick fix

#651 feat: calendar
  images/calendar_placeholder.png
  package-lock.json
  package.json
  src/App/routerViewsConfig.js
  src/App/styles.less
  src/common/BottomSheet/BottomSheet.less
  src/common/BottomSheet/BottomSheet.tsx
  src/common/BottomSheet/index.ts
  src/common/Chips/Chip/Chip.less
  src/common/Chips/Chips.less
  src/common/Chips/Chips.tsx
  src/common/HorizontalScroll/HorizontalScroll.less
  src/common/HorizontalScroll/HorizontalScroll.tsx
  src/common/HorizontalScroll/index.ts
  src/common/MainNavBars/MainNavBars.js
  src/common/NavBar/VerticalNavBar/styles.less
  src/common/PaginationInput/PaginationInput.js
  src/common/PaginationInput/index.js
  src/common/PaginationInput/styles.less
  src/common/animations.less
  src/common/index.js
  src/common/routesRegexp.js
  src/modules.d.ts
  src/routes/Calendar/Calendar.less
  src/routes/Calendar/Calendar.tsx
  src/routes/Calendar/Details/Details.less
  src/routes/Calendar/Details/Details.tsx
  src/routes/Calendar/Details/index.ts
  src/routes/Calendar/List/Item/Item.less
  src/routes/Calendar/List/Item/Item.tsx
  src/routes/Calendar/List/Item/index.ts
  src/routes/Calendar/List/List.less
  src/routes/Calendar/List/List.tsx
  src/routes/Calendar/List/index.ts
  src/routes/Calendar/Placeholder/Placeholder.less
  src/routes/Calendar/Placeholder/Placeholder.tsx
  src/routes/Calendar/Placeholder/index.ts
  src/routes/Calendar/Selector/Selector.less
  src/routes/Calendar/Selector/Selector.tsx
  src/routes/Calendar/Selector/index.ts
  src/routes/Calendar/Table/Cell/Cell.less
  src/routes/Calendar/Table/Cell/Cell.tsx
  src/routes/Calendar/Table/Cell/index.ts
  src/routes/Calendar/Table/Table.less
  src/routes/Calendar/Table/Table.tsx
  src/routes/Calendar/Table/index.ts
  src/routes/Calendar/index.ts
  src/routes/Calendar/useCalendar.ts
  src/routes/Calendar/useCalendarDate.ts
  src/routes/Discover/styles.less
  src/routes/index.js
  src/services/KeyboardShortcuts/KeyboardShortcuts.js
  src/types/models/Calendar.d.ts
Labels: enhancement
