Repository Stremio/stremio-web, pull requests merged in 2024-12, with the labels that each got.

#707 Feat: Manage multiple streaming URLs in the Settings
  package-lock.json
  package.json
  src/common/CONSTANTS.js
  src/common/Checkbox/index.js
  src/common/NavBar/HorizontalNavBar/SearchBar/SearchBar.js
  src/common/RadioButton/RadioButton.less
  src/common/RadioButton/RadioButton.tsx
  src/common/RadioButton/index.ts
  src/common/SearchBar/SearchBar.js
  src/common/SharePrompt/SharePrompt.js
  src/common/TextInput/TextInput.js
  src/common/TextInput/TextInput.tsx
  src/common/TextInput/index.js
  src/common/TextInput/index.ts
  src/common/Toggle/Toggle.js
  src/common/Toggle/index.js
  src/common/Toggle/styles.less
  src/common/index.js
  src/routes/Intro/ConsentCheckbox/index.js
  src/routes/Intro/ConsentToggle/ConsentToggle.js
  src/routes/Intro/ConsentToggle/index.js
  src/routes/Intro/ConsentToggle/styles.less
  src/routes/Intro/CredentialsTextInput/CredentialsTextInput.js
  src/routes/Intro/Intro.js
  src/routes/MetaDetails/VideosList/VideosList.js
  src/routes/MetaDetails/VideosList/styles.less
  src/routes/Player/ControlBar/ControlBar.js
  src/routes/Settings/Settings.js
  src/routes/Settings/URLsManager/AddItem/AddItem.less
  src/routes/Settings/URLsManager/AddItem/AddItem.tsx
  src/routes/Settings/URLsManager/AddItem/index.ts
  src/routes/Settings/URLsManager/Item/Item.less
  src/routes/Settings/URLsManager/Item/Item.tsx
  src/routes/Settings/URLsManager/Item/index.ts
  src/routes/Settings/URLsManager/URLsManager.less
  src/routes/Settings/URLsManager/URLsManager.tsx
  src/routes/Settings/URLsManager/index.ts
  src/routes/Settings/URLsManager/useStreamingServerUrls.js
  src/routes/Settings/styles.less
  src/routes/Settings/useProfileSettingsInputs.js
  src/types/models/Ctx.d.ts
Labels: enhancement

#733 fix: settings navigate between menus shortcut
  src/routes/Settings/Settings.js
Labels: quick fix

#737 feat: create issue templates for bugs and features
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement

#738 Feat: Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement

#740 fix: nav-menu height
  src/common/NavBar/HorizontalNavBar/NavMenu/styles.less
Labels: quick fix

#742 fix: multiselectMenu and Multiselect height
  src/common/ModalDialog/styles.less
  src/common/Multiselect/styles.less
  src/common/MultiselectMenu/Dropdown/Dropdown.less
  src/routes/Addons/styles.less
  src/routes/Discover/styles.less
  src/routes/Library/styles.less
  src/routes/MetaDetails/StreamsList/styles.less
  src/routes/MetaDetails/VideosList/SeasonsBar/styles.less
Labels: quick fix

#746 refactor (URLsmanager): styles
  src/common/RadioButton/RadioButton.less
  src/routes/Settings/URLsManager/Item/Item.less
  src/routes/Settings/URLsManager/URLsManager.less
Labels: design

#751 fix: remove blue select box from the buttons
  src/common/Button/styles.less
  src/common/RadioButton/RadioButton.less
Labels: quick fix

#752 fix: colorInput component styles
  src/common/ColorInput/styles.less
  src/routes/Settings/styles.less
Labels: quick fix

#748 refactor: remove addons button horizontal navbar
  src/common/MainNavBars/MainNavBars.js
  src/common/NavBar/HorizontalNavBar/HorizontalNavBar.js
  src/routes/MetaDetails/MetaDetails.js
Labels: refactor

#758 fix: styles on event modal
  src/common/EventModal/styles.less
Labels: quick fix

#756 refactor: rewrite sidedrawer to act like a menu
  src/common/Transition/Transition.tsx
  src/common/Transition/index.ts
  src/common/animations.less
  src/common/index.js
  src/routes/Player/Player.js
  src/routes/Player/SideDrawer/SideDrawer.less
  src/routes/Player/SideDrawer/SideDrawer.tsx
  src/routes/Player/SideDrawer/index.ts
  src/routes/Player/SideDrawerButton/SideDrawerButton.less
  src/routes/Player/SideDrawerButton/SideDrawerButton.tsx
  src/routes/Player/SideDrawerButton/index.ts
  src/routes/Player/styles.less
  src/types/models/Player.d.ts
Labels: refactor

#759 fix: toats outer glow problem with overflow
  src/App/styles.less
Labels: quick fix

#760 feat: addon placeholder
  src/routes/Addons/AddonPlaceholder/AddonPlaceholder.less
  src/routes/Addons/AddonPlaceholder/AddonPlaceholder.tsx
  src/routes/Addons/AddonPlaceholder/index.ts
  src/routes/Addons/Addons.js
Labels: enhancement

#762 Fix: Correct URL Encoding in SearchBar Component
  src/common/NavBar/HorizontalNavBar/SearchBar/SearchBar.js
Labels: quick fix

#761 fix: streaming server url AddItem styles
  src/routes/Settings/URLsManager/AddItem/AddItem.less
Labels: quick fix

#764 fix: modal image was not visible on some macbooks
  src/common/EventModal/styles.less
Labels: quick fix

#769 Fix Poster Sharpness
  src/common/MetaItem/styles.less
Labels: quick fix

#772 fix: scroll top safari issues
  src/routes/MetaDetails/StreamsList/StreamsList.js
Labels: quick fix

#735 feat: Side Drawer component implementation inside the Player
  package-lock.json
  package.json
  src/common/Transition/Transition.tsx
  src/common/Transition/index.ts
  src/common/animations.less
  src/common/index.js
  src/routes/MetaDetails/VideosList/SeasonsBar/styles.less
  src/routes/Player/ControlBar/ControlBar.js
  src/routes/Player/ControlBar/styles.less
  src/routes/Player/InfoMenu/InfoMenu.js
  src/routes/Player/InfoMenu/index.js
  src/routes/Player/InfoMenu/styles.less
  src/routes/Player/Player.js
  src/routes/Player/SideDrawer/SideDrawer.less
  src/routes/Player/SideDrawer/SideDrawer.tsx
  src/routes/Player/SideDrawer/index.ts
  src/routes/Player/SideDrawerButton/SideDrawerButton.less
  src/routes/Player/SideDrawerButton/SideDrawerButton.tsx
  src/routes/Player/SideDrawerButton/index.ts
  src/routes/Player/VideosMenu/index.js
  src/routes/Player/VideosMenu/styles.less
  src/routes/Player/styles.less
  src/types/MetaItem.d.ts
  src/types/Video.d.ts
  src/types/models/Player.d.ts
Labels: enhancement

#739 Player: move audio tracks to their own menu
  package-lock.json
  package.json
  src/routes/Player/AudioMenu/AudioMenu.less
  src/routes/Player/AudioMenu/AudioMenu.tsx
  src/routes/Player/AudioMenu/index.ts
  src/routes/Player/ControlBar/ControlBar.js
  src/routes/Player/Player.js
  src/routes/Player/SubtitlesMenu/SubtitlesMenu.js
  src/routes/Settings/Settings.js
  src/types/types.d.ts
Labels: enhancement, refactor

#775 Player: add label to audio tracks
  src/routes/Player/AudioMenu/AudioMenu.less
  src/routes/Player/AudioMenu/AudioMenu.tsx
Labels: enhancement

#776 Player: fix subtitles tracks layout
  src/routes/Player/SubtitlesMenu/SubtitlesMenu.js
  src/routes/Player/SubtitlesMenu/styles.less
Labels: quick fix, refactor
