Repository Stremio/stremio-web, pull requests merged in 2025-05, with the labels that each got.

#903 Player(Shell): Fix binge watching bugs
  src/routes/Player/Player.js
Labels: bug

#908 Search: align styles with board catalogs
  src/routes/Search/styles.less
Labels: refactor

#906 fix: StatisticsMenu - max of 100% for completed
  src/routes/Player/StatisticsMenu/StatisticsMenu.js
Labels: bug

#907 fix: exitFullscreen
  src/common/useFullscreen.ts
Labels: bug

#864 Refactor: Replace Multiselect with MultiselectMenu component
  src/components/MultiselectMenu/Dropdown/Dropdown.tsx
  src/components/MultiselectMenu/MultiselectMenu.less
  src/components/MultiselectMenu/MultiselectMenu.tsx
  src/routes/Addons/Addons.js
  src/routes/Addons/styles.less
  src/routes/Addons/useSelectableInputs.js
  src/routes/Discover/Discover.js
  src/routes/Discover/styles.less
  src/routes/Discover/useSelectableInputs.js
  src/routes/Library/Library.js
  src/routes/Library/styles.less
  src/routes/Library/useSelectableInputs.js
  src/routes/MetaDetails/StreamsList/StreamsList.js
  src/routes/MetaDetails/StreamsList/styles.less
Labels: refactor

#919 App(Shell): toggle fullscreen with F key
  src/common/useFullscreen.ts
  src/services/KeyboardShortcuts/KeyboardShortcuts.js
Labels: enhancement

#921 App(Shell): full deeplink support
  src/App/App.js
  src/common/CONSTANTS.js
  src/common/routesRegexp.js
Labels: enhancement

#917 Settings: fix trakt logout button
  src/routes/Settings/Settings.js
Labels: bug
