Repository Stremio/stremio-web, pull requests merged in 2025-06, with the labels that each got.

#922 refactor(common): remove use of ipc for opening external url
  src/common/Platform/Platform.tsx
Labels: refactor

#855 Аpp: Replace Multiselect usage with MultiselectMenu
  src/components/MultiselectMenu/Dropdown/Dropdown.tsx
  src/components/MultiselectMenu/Dropdown/Option/Option.tsx
  src/components/MultiselectMenu/MultiselectMenu.less
  src/components/MultiselectMenu/MultiselectMenu.tsx
  src/routes/Addons/Addons.js
  src/routes/Addons/styles.less
  src/routes/Addons/useSelectableInputs.js
  src/routes/Discover/Discover.js
  src/routes/Discover/styles.less
  src/routes/Discover/useSelectableInputs.js
  src/routes/Library/Library.js
  src/routes/Library/styles.less
  src/routes/Library/useSelectableInputs.js
  src/routes/MetaDetails/StreamsList/StreamsList.js
  src/routes/MetaDetails/StreamsList/styles.less
  src/routes/MetaDetails/VideosList/SeasonsBar/SeasonsBar.js
  src/routes/Settings/Settings.js
  src/routes/Settings/styles.less
  src/routes/Settings/useProfileSettingsInputs.js
  src/routes/Settings/useStreamingServerSettingsInputs.js
Labels: refactor

#937 fix(SideDrawer): mobile styles
  src/components/MultiselectMenu/Dropdown/Dropdown.less
  src/routes/Player/SideDrawer/SideDrawer.less
Labels: bug

#938 Player: add subtitles delay shortcuts
  package-lock.json
  package.json
  src/common/animations.less
  src/routes/Player/Indicator/Indicator.less
  src/routes/Player/Indicator/Indicator.tsx
  src/routes/Player/Player.js
  src/routes/Player/styles.less
  src/routes/Settings/Settings.js
Labels: feature

#942 refactor(Shell): remove init logic
  src/services/Shell/Shell.js
  src/services/Shell/ShellTransport.js
Labels: refactor

#914 Shell: Fix binge watching flow
  src/routes/Player/Player.js
Labels: bug

#933 Settings: Default langs priority and Alphabetic Ordering
  src/common/index.js
  src/common/useLanguageSorting.ts
  src/routes/Settings/General/useGeneralOptions.ts
  src/routes/Settings/Player/usePlayerOptions.ts
Labels: feature

#957 fix(MetaDetails): trailers button crash
  src/routes/Player/Player.js
Labels: bug

#958 App(Search): fullscreen shortcut interference
  src/common/useFullscreen.ts
Labels: bug
