Repository Stremio/stremio-web, pull requests merged in 2025-03, with the labels that each got.

#860 Settings: use correct prop for button
  src/routes/Settings/URLsManager/URLsManager.tsx
Labels: bug

#871 App(Shell): support opening addons from deeplink
  src/App/App.js
Labels: feature

#851 Player: Improve volume UX on mobile and tablets
  src/components/Slider/Slider.js
  src/routes/Player/ControlBar/ControlBar.js
  src/routes/Player/Player.js
Labels: enhancement

#874 chore: ControlBar & VolumeChangeIndicator show volume=0 with muted icon
  src/routes/Player/ControlBar/ControlBar.js
  src/routes/Player/VolumeChangeIndicator/VolumeChangeIndicator.js
Labels: bug

#875 Calendar: Implement Item placeholder
  src/routes/Calendar/List/Item/Item.less
  src/routes/Calendar/List/Item/ItemPlaceholder.tsx
  src/routes/Calendar/List/Item/index.ts
  src/routes/Calendar/List/List.tsx
Labels: feature

#813 Player: add context menu
  src/components/ContextMenu/ContextMenu.less
  src/components/ContextMenu/ContextMenu.tsx
  src/components/ContextMenu/index.ts
  src/components/index.ts
  src/routes/Player/BufferingLoader/BufferingLoader.js
  src/routes/Player/Error/Error.js
  src/routes/Player/OptionsMenu/OptionsMenu.js
  src/routes/Player/Player.js
  src/routes/Player/useVideo.js
Labels: feature
