Repository Stremio/stremio-web, pull requests merged in 2025-01, with the labels that each got.

#778 feat(MultiSelectMenu): scroll into view
  src/common/MultiselectMenu/Dropdown/Dropdown.tsx
  src/common/MultiselectMenu/Dropdown/Option/Option.tsx
Labels: enhancement

#765 refactor(styles): improve PWA styles on mobile devices (1)
  src/App/styles.less
  src/common/BottomSheet/BottomSheet.less
  src/common/Button/styles.less
  src/common/Chips/Chip/Chip.less
  src/common/MainNavBars/styles.less
  src/common/MetaItem/styles.less
  src/common/NavBar/HorizontalNavBar/styles.less
  src/common/NavBar/VerticalNavBar/NavTabButton/styles.less
  src/common/RadioButton/RadioButton.less
  src/index.html
  src/routes/Addons/styles.less
  src/routes/Board/styles.less
  src/routes/Calendar/Details/Details.less
  src/routes/Calendar/Selector/Selector.less
  src/routes/Calendar/Table/Cell/Cell.less
  src/routes/Discover/styles.less
  src/routes/Library/styles.less
  src/routes/MetaDetails/MetaDetails.js
  src/routes/MetaDetails/styles.less
  src/routes/Search/styles.less
  src/routes/Settings/styles.less
Labels: refactor

#779 fix(Board): Hide empty catalogs
  src/routes/Board/Board.js
Labels: quick fix

#782 fix(RadioButton): inner circle position
  src/common/RadioButton/RadioButton.less
Labels: quick fix

#783 Refactor/calendar styles
  src/routes/Calendar/Calendar.less
  src/routes/Calendar/Table/Cell/Cell.less
  src/routes/Calendar/Table/Cell/Cell.tsx
Labels: quick fix, refactor

#796 fix(App): PWA resizing issues
  src/App/styles.less
Labels: quick fix

#785 fix(App): make route switching animation feel smoother
  src/common/animations.less
Labels: quick fix

#799 fix(Calendar): add missing route animation
  src/routes/Calendar/Calendar.tsx
Labels: quick fix

#800 fix(App): older iOS versions support
  src/App/styles.less
Labels: quick fix

#795 refactor(MetaDetails): landscape mobile styles
  src/common/screen-sizes.less
  src/components/MetaPreview/ActionButton/styles.less
  src/components/MetaPreview/styles.less
  src/routes/MetaDetails/styles.less
Labels: enhancement, refactor

#797 refactor(NavBar): improve navigation buttons contrast
  src/components/NavBar/HorizontalNavBar/styles.less
  src/components/NavBar/VerticalNavBar/NavTabButton/styles.less
Labels: refactor

#802 fix(Search): hide empty catalog rows
  src/routes/Search/Search.js
Labels: quick fix

#803 refactor(NextVideoPopup): remove desc & styles
  src/common/screen-sizes.less
  src/routes/Player/NextVideoPopup/NextVideoPopup.js
  src/routes/Player/NextVideoPopup/styles.less
Labels: refactor

#741 Details: Hide install addons button for older accounts
  package-lock.json
  package.json
  src/routes/MetaDetails/StreamsList/StreamsList.js
  src/routes/MetaDetails/StreamsList/styles.less
  src/types/models/Ctx.d.ts
Labels: refactor

#784 PWA: fix maskable icon
  webpack.config.js
Labels: quick fix

#786 Board: update the style of the streaming server warning
  src/routes/Board/Board.js
  src/routes/Board/StreamingServerWarning/StreamingServerWarning.js
  src/routes/Board/StreamingServerWarning/StreamingServerWarning.less
  src/routes/Board/StreamingServerWarning/StreamingServerWarning.tsx
  src/routes/Board/StreamingServerWarning/index.js
  src/routes/Board/StreamingServerWarning/index.ts
  src/routes/Board/StreamingServerWarning/styles.less
  src/routes/Board/styles.less
Labels: refactor

#805 StreamingServerWarning: hide when server is online
  src/routes/Board/Board.js
Labels: quick fix

#806 Player: fix side drawer button position
  src/routes/Player/styles.less
Labels: quick fix

#809 Board: Fix streaming server warning on mobile
  src/routes/Board/styles.less
Labels: bug

#808 PWA: Fix mobile devices style issues
  src/App/styles.less
  src/components/BottomSheet/BottomSheet.less
  src/components/MainNavBars/MainNavBars.less
  src/routes/Addons/styles.less
  src/routes/Board/styles.less
  src/routes/Calendar/Calendar.less
  src/routes/Discover/styles.less
  src/routes/Library/styles.less
  src/routes/MetaDetails/styles.less
  src/routes/Settings/styles.less
Labels: bug

#811 SideDrawer: improve mobile styles
  src/routes/Player/SideDrawer/SideDrawer.less
Labels: bug, enhancement

#815 build: remove commit hash from images path
  webpack.config.js
Labels: bug
