Repository Stremio/stremio-web, pull requests merged in 2025-02, with the labels that each got.

#820 MetaDetails: Add stream title and icons on context menu
  src/routes/MetaDetails/StreamsList/Stream/Stream.js
  src/routes/MetaDetails/StreamsList/Stream/styles.less
Labels: feature

#789 Player: Allow to drop local subtitles
  package-lock.json
  package.json
  src/App/App.js
  src/App/styles.less
  src/common/CONSTANTS.js
  src/common/FileDrop/FileDrop.tsx
  src/common/FileDrop/index.ts
  src/common/FileDrop/onFileDrop.ts
  src/common/FileDrop/utils.ts
  src/common/index.js
  src/routes/Player/Player.js
  src/routes/Player/SubtitlesMenu/SubtitlesMenu.js
  src/routes/Player/useVideo.js
  src/services/DragAndDrop/DragAndDrop.js
Labels: feature

#824 App: support video hardware decoding
  src/routes/Player/Player.js
  src/routes/Settings/Settings.js
Labels: feature

#830 Vertical Navbar: Adjust icons to prevent cutting on mobile
  src/components/NavBar/VerticalNavBar/styles.less
Labels: bug

#829 Player: Subtitles Settings scrollable on mobile
  src/routes/Player/SubtitlesMenu/SubtitlesMenu.js
  src/routes/Player/SubtitlesMenu/styles.less
Labels: bug

#832 Intro: Consent items using checkbox instead toggle
  src/components/Button/Button.tsx
  src/components/Checkbox/Checkbox.less
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/index.ts
  src/components/index.ts
  src/routes/Intro/ConsentToggle/ConsentToggle.js
  src/routes/Intro/ConsentToggle/index.js
  src/routes/Intro/ConsentToggle/styles.less
  src/routes/Intro/Intro.js
Labels: enhancement

#833 Calendar: Fix items scroll in view to ensure borders remain visible
  src/routes/Calendar/List/Item/Item.less
  src/routes/Calendar/List/List.less
Labels: bug

#837 Player: Improve Seek Bar Contrast for Better Visibility
  src/components/Slider/styles.less
Labels: enhancement

#831 Board: Ensure user panel is visible correctly when the server warning is not dismissed
  src/components/NavBar/HorizontalNavBar/NavMenu/NavMenuContent.js
  src/components/NavBar/HorizontalNavBar/NavMenu/styles.less
Labels: bug

#843 Checkbox: remove transition on outline on hover/focus
  src/components/Checkbox/Checkbox.less
Labels: enhancement

#842 Library: Align Guest placeholder with Calendar guest placeholder
  images/library_placeholder.png
  src/routes/Library/Library.js
  src/routes/Library/Placeholder/Placeholder.less
  src/routes/Library/Placeholder/Placeholder.tsx
  src/routes/Library/Placeholder/index.ts
  src/routes/Library/styles.less
Labels: enhancement

#846 Intro: Improve layout responsiveness on smaller screens
  src/routes/Intro/styles.less
Labels: enhancement

#848 fix(Calendar): iPad Safari styles
  src/routes/Calendar/Calendar.less
Labels: bug

#850 Board/Search: Show catalog names while loading
  src/routes/Board/Board.js
  src/routes/Search/Search.js
Labels: enhancement
